#!/bin/bash

for ARG in "$@"
do
	if [ $ARG == '-t' ]; then
		pip install -r test_requirements.txt -q
	fi
	if [ $ARG == '-u' ]; then
		# Uninstall previous version
		pip uninstall tidehunter -yq
	fi
done

# Clean up
rm -rf 'tidehunter.egg-info/'
rm -rf dist/

# Package
python setup.py -q sdist

# Deploy
pip install dist/tidehunter* -q

# Clean up
rm -rf 'tidehunter.egg-info/'
rm -rf dist/
